main/urls.py
from django.conf.urls import url

from main.views import (
    WeeklyMenuView, HomeView, LoginView, RegistrationView, LogoutView, AccountView, ChangePasswordView,
    ChangeAmountView, PurchasingView, OrderInfoView, CurrentPointView)

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^weekly_menu/$', WeeklyMenuView.as_view(), name='weekly_menu'),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^account/$', AccountView.as_view(), name='account'),
    url(r'^change_password/$', ChangePasswordView.as_view(), name='change_password'),
    url(r'^change_amount/(\d+)/$', ChangeAmountView.as_view(), name='change_amount'),
    url(r'^purchasing/$', PurchasingView.as_view(), name='purchasing'),
    url(r'^order_info/(\d+)/$', OrderInfoView.as_view(), name='order_info'),
    url(r'^current_point/(\d+)/$', CurrentPointView.as_view(), name='current_point')
]

smena/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from django.conf import settings

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

from dishes.models import Dinner


class Client(models.Model):
    phone = models.CharField(max_length=15, unique=True)
    user = models.OneToOneField(User)


class Address(models.Model):
    address = models.CharField(max_length=512, null=False)
    geo_lat = models.CharField(max_length=50, null=True)
    geo_lon = models.CharField(max_length=50, null=True)
    client = models.ForeignKey(Client, related_name='addresses')


class Basket(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client, null=True)
    address = models.ForeignKey(Address, null=True)
    delivery_at = models.DateTimeField(null=True)
    order_date = models.DateTimeField(null=True)
    route_id = models.IntegerField(null=True)

    def sum(self):
        summary = 0
        for basket_item in self.items.all():
            summary += basket_item.price * basket_item.quantity
        return summary

    def quantity(self):
        quantity = 0
        for basket_item in self.items.all():
            quantity += basket_item.quantity
        return quantity


class BasketItem(models.Model):
    basket = models.ForeignKey(Basket, related_name='items')
    dinner = models.ForeignKey(Dinner)
    quantity = models.IntegerField(default=0)
    price = models.FloatField(default=0)

    def sum(self):
        return self.quantity * self.price


class SmsCode(models.Model):
    phone = models.CharField(max_length=15, unique=True)
    sms_code = models.IntegerField(null=True)
    modified = models.DateTimeField(auto_now=True)

main/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from main.utils import clean_phone


class SmsForm(forms.Form):
    phone = forms.CharField(max_length=16, error_messages={'required': 'Введите номер телефона'})

    def clean_phone(self):
        phone = clean_phone(self.cleaned_data['phone'])
        if phone:
            return phone
        else:
            raise forms.ValidationError('Введите номер телефона')


class RegistrationForm(forms.Form):
    phone = forms.CharField(max_length=16, error_messages={'required': 'Введите номер телефона'})
    password = forms.CharField(max_length=255, error_messages={'required': 'Введите пароль'})
    sms_code = forms.CharField(error_messages={'required': 'Введите код из sms'})

    def clean_phone(self):
        phone = clean_phone(self.cleaned_data['phone'])
        if phone:
            return phone
        else:
            raise forms.ValidationError('Введите номер телефона')


class LoginForm(forms.Form):
    phone = forms.CharField(max_length=16, error_messages={'required': 'Введите номер телефона'})
    password = forms.CharField(max_length=255, error_messages={'required': 'Введите пароль'})

    def clean_phone(self):
        phone = clean_phone(self.cleaned_data['phone'])
        if phone:
            return phone
        else:
            raise forms.ValidationError('Введите номер телефона')


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(max_length=255, error_messages={'required': 'Введите старый пароль'})
    new_password = forms.CharField(max_length=255, error_messages={'required': 'Введите новый пароль'})
    new_password_repeat = forms.CharField(max_length=255, error_messages={'required': 'Повторите новый пароль'})

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        new_password = cleaned_data.get('new_password')
        new_password_repeat = cleaned_data.get('new_password_repeat')

        if new_password != new_password_repeat:
            raise forms.ValidationError('Пароли не совпадают')

        return cleaned_data

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import random
from datetime import timedelta, date, time, datetime

import requests
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template.defaulttags import register
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from main.utils import sms_code_is_valid, get_mon_fri_of_current_week, create_basket_item, clean_phone, form_response

from dishes.models import DailyMenu
from main.forms import LoginForm, RegistrationForm, ChangePasswordForm, SmsForm
from main.models import Client, Basket, BasketItem, Address, SmsCode


class WeeklyMenuView(View):
    template_name = 'main/weekly_menu.html'

    def get(self, request):
        today = date.today()
        if today.weekday() in [5, 6]:
            mon, fri = get_mon_fri_of_current_week(today + timedelta(days=2))
        else:
            mon, fri = get_mon_fri_of_current_week(today)
        weekly_menu = DailyMenu.objects.filter(date__gte=mon, date__lte=fri).prefetch_related('dinners')
        context = {
            'today': today,
            'monday_date': mon,
            'friday_date': fri,
            'weekly_menu': weekly_menu
        }
        return render(request, self.template_name, context)


class HomeView(View):
    template_name = 'main/home.html'

    def get(self, request):
        try:
            daily_menu = DailyMenu.objects.get(date=date.today())
        except DailyMenu.DoesNotExist:
            daily_menu = False
        dinners = daily_menu.dinners.all() if daily_menu else False
        basket = request.basket
        basket_dict = {} if basket else False
        if basket and dinners:
            for dinner in dinners:
                try:
                    basket_item = BasketItem.objects.get(basket=basket, dinner=dinner)
                except BasketItem.DoesNotExist:
                    basket_item = False
                quantity = basket_item.quantity if basket_item else 0
                basket_dict[dinner.id] = quantity
        context = {
            'today': date.today(),
            'dinners': dinners,
            'basket_dict': basket_dict
        }
        return render(request, self.template_name, context)


class LoginView(View):
    def post(self, request):
        status = False
        form = LoginForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data['phone']
            password = form.cleaned_data['password']
            try:
                Client.objects.get(phone=phone)
                user = authenticate(request, username=phone, password=password)
                if user:
                    login(request, user)
                    status = True
                    messages.success(request, 'Авторизация успешно выполнена')
                else:
                    messages.error(request, 'Неверная пара логин/пароль')

            except Client.DoesNotExist:
                messages.error(request, 'Пользователь с данным номером телефона не зарегистрирован')
        return form_response(request, form, status, 'home')


class RegistrationView(View):

    def post(self, request):
        is_sms = bool(request.POST.get('action') == 'send_sms')
        status = False
        form = SmsForm(request.POST) if is_sms else RegistrationForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data['phone']
            if Client.objects.filter(phone=phone):
                messages.error(request, 'Пользователь с данным номером телефона уже существует')
            elif is_sms:
                sms_code = str(random.randrange(100000, 999999))
                try:
                    sms_code_object = SmsCode.objects.get(phone=phone)
                except SmsCode.DoesNotExist:
                    sms_code_object = SmsCode.objects.create(phone=phone)
                sms_code_object.sms_code = sms_code
                sms_code_object.save()
                params = {
                    'api_id': 'f567a71e-f7b2-c134-0da6-4c6bbd49602b',
                    'to': phone,
                    'msg': 'code: ' + sms_code,
                    'json': 1
                }
                content = requests.post('https://sms.ru/sms/send/', params=params).json()
                if content['status'] == 'OK':
                    status = True
                    messages.success(request, 'Код успешно отправлен в sms')
                else:
                    messages.error(request, 'Не удалось отправить sms')
            else:
                password = form.cleaned_data['password']
                sms_code = str(form.cleaned_data['sms_code'])

                if not sms_code_is_valid(sms_code, phone):
                    messages.error(request, 'Введен не правильный код')
                else:
                    user = User.objects.create_user(username=phone, password=password)
                    Client.objects.create(phone=phone, user=user)
                    login(request, user)
                    messages.success(request, 'Регистрация успешно завершена')
                    status = True
        return form_response(request, form, status, 'home')


class LogoutView(View):
    def post(self, request):
        basket_id = request.session.get('basket_id')
        logout(request)
        #messages.error(request, 'Выход выполнен')
        if basket_id:
            request.session['basket_id'] = basket_id
        return redirect('home')


class AccountView(View):
    template_name = 'main/account.html'

    @method_decorator(login_required())
    def get(self, request):
        order_list = Basket.objects.filter(order_date__isnull=False, client=request.user.client).order_by('-order_date')
        paginator = Paginator(order_list, 10)
        page = request.GET.get('page')
        try:
            orders = paginator.page(page)
        except PageNotAnInteger:
            orders = paginator.page(1)
        context = {
            'orders': orders
        }
        return render(request, self.template_name, context)


class ChangePasswordView(View):
    @method_decorator(login_required())
    def post(self, request):
        status = False
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            user = authenticate(request,
                                username=request.user.username,
                                password=old_password)
            if not user:
                messages.error(request, 'Текущий пароль введен неверно')
            else:
                user.set_password(new_password)
                user.save()
                login(request, user)
                messages.success(request, 'Пароль успешно изменен')
                status = True
        return form_response(request, form, status, 'account')


class ChangeAmountView(View):
    def post(self, request, item_id):
        basket = request.basket
        amount = int(request.POST.get('amount'))
        context = {
            'status': False,
            'amount': 0
        }
        if item_id:
            item = create_basket_item(basket, item_id)
            quantity = item.quantity + amount
            item.quantity = quantity if quantity > 0 else 0
            item.save()
            context['status'] = True
            context['amount'] = item.quantity
        if request.is_ajax():
            context['basket_sum'] = basket.sum()
            context['basket_amount'] = basket.quantity()
            return JsonResponse(context)
        return redirect('home')


class PurchasingView(View):
    def post(self, request):
        basket = request.basket
        address = request.POST.get('address')
        geo_lat = request.POST.get('address_geo_lat')
        geo_lon = request.POST.get('address_geo_lon')
        try:
            minutes = int(request.POST.get('minutes'))
        except ValueError:
            minutes = False
        try:
            hours = int(request.POST.get('hours'))
        except ValueError:
            hours = False
        is_complete = False
        url = ''

        address_object = False
        if geo_lat and geo_lon:
            address_object = Address.objects.create(
                address=address,
                geo_lat=request.POST.get('address_geo_lat'),
                geo_lon=request.POST.get('address_geo_lon'),
                client=request.user.client
            )
            response = requests.post(
                'http://95.213.141.29/route/create/',
                headers={'host': 'cme.frfrdev.ru'},
                data={'lat': geo_lat, 'lon': geo_lon}
            )
            if response.status_code == 200:
                content = response.json()
                basket.route_id = content['id']
                basket.save()
        elif address:
            address_object = Address.objects.create(
                address=address,
                client=request.user.client
            )

        if address_object:
            basket.address = address_object
            basket.save()

        if minutes and hours:
            basket.delivery_at = datetime.combine(date.today(), time(hours, minutes))

        if basket.address and minutes and hours:
            basket.order_date = datetime.now()
            basket.save()
            del request.session['basket_id']
            is_complete = True
            url = reverse('order_info', args=[basket.id])

        if request.is_ajax():
            context = {
                'status': is_complete,

main/templates/main/account.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Личный кабинет
{% endblock %}

{% block content %}
    <div class="persona">
        <div class="layout__inner">
            <div class="persona__inner">
                <div class="persona__title">Личный кабинет</div>
                <div class="persona__cont">
                    <div class="persona__left">
                        <div class="persona__history">
                            <div class="history">
                                <div class="history__title">ИСТОРИЯ ЗАКАЗОВ</div>
                                <div class="history__cont">
                                    <div class="history__table">
                                        <table class="paginated">
                                            <thead>
                                            <tr>
                                                <th scope="col" style="width:30%">Дата</th>
                                                <th scope="col" style="width:40%">Стоимость, р.</th>
                                                <th scope="col" style="width:30%">Статус</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                {% for order in orders %}
                                                    <tr>
                                                        <td class="history__date"><a href="{% url 'order_info' order.id %}">{{ order.order_date|date:"d.m.Y" }}</a></td>
                                                        <td>{{ order.sum|floatformat }}</td>
                                                        <td data-status="work" class="history__status"></td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="pager">
                                        <a class="page__control page__first"></a>
                                        <a class=" page__control page__prev"></a>
                                        <a class=" page__control page__next"></a>
                                        <a class=" page__control page__last"></a>
                                        <div class="pager__box">
                                            {% for page in orders.paginator.page_range %}
                                                {% if orders.number == page %}
                                                    <span class="page-number clickable active">{{ page }}</span>
                                                {% else %}
                                                    <a href="?page={{ page }}" class="page-number clickable">{{ page }}</a>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="persona__options">
                            <div class="options">
                                <div class="options__title">НАСТРОЙКИ</div>
                                <form action="{% url 'change_password' %}" method="post" class="options__form js-password-form">
                                    {% csrf_token %}
                                    <div class="options__line">
                                        <div data-input="Текущий пароль" class="input__cont">
                                            <input id="id_old_password" name="old_password" type="password" class="input__this"/>
                                        </div>
                                    </div>
                                    <div class="options__line">
                                        <div data-input="Новый пароль" class="input__cont">
                                            <input id="id_new_password" name="new_password" type="password" class="input__this"/>
                                        </div>
                                    </div>
                                    <div class="options__line">
                                        <div data-input="Повторить новый пароль" class="input__cont">
                                            <input id="id_new_password_repeat" name="new_password_repeat" type="password" class="input__this"/>
                                        </div>
                                    </div>
                                    <div class="options__bottom">
                                        <button class="button">СОХРАНИТЬ</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="persona__right">
                        <div class="statham">
                            <div class="statham__item"><img src="{% static 'img/design/statham_01.png' %}"/></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    <div class="hero">
        <div style="background-image:url({% static 'img/design/main.png' %})" class="hero__image"></div>
        <div class="layout__inner">
            <div class="hero__cont">
                <div class="hero__text">доставка <span>обедов</span></div>
            </div>
            <div class="hero__bottom">
                <a href="#today_menu" class="hero__bottom-text">СМОТРИ МЕНЮ НА СЕГОДНЯ<span></span></a>
            </div>
        </div>
    </div>
    <div class="menu" id="today_menu">
        <div class="layout__inner">
            <div class="menu__cont">
                {% for dinner in dinners.all %}
                    {% include 'main/inc/menu_item.html' with basket_dict=basket_dict %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="order">
        <div class="form" id="form">
            {% if messages %}
                <div class="form-messages">
                    <div><b>Сообщения:</b></div>
                    <ul>
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if not user.is_authenticated %}
                <div class="form__tab">
                    <div data-tab="tab_1" class="form__tab-item active">ВХОД</div>
                    <div data-tab="tab_2" class="form__tab-item">РЕГИСТРАЦИЯ</div>
                </div>
                <div data-tab="tab_1" class="form__item active">
                    <form class="form__this js-login-form" action="{% url 'login' %}" method="post">
                        {% csrf_token %}
                        <div class="form__line">
                            <div data-input="Номер телефона" class="input__cont input__phone">
                                <input name="phone" class="input__this input__this-phone"/>
                            </div>
                        </div>
                        <div class="form__line">
                            <div data-input="Пароль" class="input__cont">
                                <input name="password" type="password" class="input__this"/>
                            </div>
                        </div>
                        <div class="form__bottom">
                            <button class="button">ПРОДОЛЖИТЬ</button>
                        </div>
                    </form>
                </div>
                <div data-tab="tab_2" class="form__item">
                    <form class="form__this js-reg-form" action="{% url 'registration' %}" method="post">
                        {% csrf_token %}
                        <div class="form__line">
                            <div data-input="Номер телефона" class="input__cont input__phone">
                                <input name="phone" class="input__this input__this-phone"/>
                            </div>
                        </div>
                        <div class="form__line form__line-sms">
                            <button type="submit" name="action" value="send_sms" class="button__sms">Выслать SMS-код</button>
                            <div class="form__sms">
                                <div class="form__sms-text">SMS-КОД:</div>
                                <div class="form__sms-right">
                                    <input name="sms_code" class="form__sms-input"/>
                                    <div class="form__sms-error" style="display: none">Неверный или пустой код</div>
                                </div>
                            </div>
                        </div>
                        <div class="form__line">
                            <div data-input="Пароль" class="input__cont">
                                <input name="password" type="password" class="input__this"/>
                            </div>
                        </div>
                        <div class="form__bottom">
                            <button type="submit" class="button">РЕГИСТРАЦИЯ</button>
                        </div>
                    </form>
                </div>
            {% else %}
                <div class="form__title">ОФОРМИТЬ ЗАКАЗ</div>
                <div class="order_address" {% if basket and basket.address %}style="display: none"{% endif %}>
                    <div class="form__desc">АДРЕС ДОСТАВКИ</div>
                    <form action="{% url 'purchasing' %}" method="post" class="form__this">
                        {% csrf_token %}
                        <div class="form__line">
                            <div data-input="Ваш адрес " class="input__cont">
                                <input id="id_address" name="address" class="input__this" required/>
                            </div>
                        </div>
                        <div class="form__more">Если все верно:</div>
                        <div class="form__bottom">
                            <button class="button" type="submit">ПРОДОЛЖИТЬ</button>
                        </div>
                    </form>
                </div>
                <div class="order_time" {% if not basket or not basket.address %}style="display: none"{% endif %}>
                    <div class="form__desc">УКАЗАТЬ ВРЕМЯ ДОСТАВКИ</div>
                    <form action="{% url 'purchasing' %}" method="post" class="form__this">
                        {% csrf_token %}
                        <div class="form__line form__line-time">
                            <div class="form__time">
                                <input id="id_hours" name="hours" placeholder="00" class="form__time-input" required/>
                            </div>
                            <div class="form__time">
                                <input id="id_minutes" name="minutes" placeholder="00" class="form__time-input" required/>
                            </div>
                        </div>
                        <div class="form__bottom">
                            <button class="button" type="submit">ПРОДОЛЖИТЬ</button>
                        </div>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

main/templates/main/order_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Информация о заказе №{{ order.id }}
{% endblock %}

{% block content %}
    <div class="detail">
        <div class="detail__inner">
            <div class="detail__title">Детали заказа № {{ order.id }}</div>
            <div class="detail__desc">
                <div class="detail__date">{{ order.order_date|date:"d.m.Y" }}</div>
                <div class="detail__time">{{ order.order_date|date:"H:i" }}</div>
            </div>
            <div class="detail__order">
                {% for basket_item in basket_items %}
                    {% if basket_item.quantity %}
                        <div class="detail__item">
                            <div class="weekly__item">
                                {% include 'main/inc/menu_item.html' with dinner=basket_item.dinner basket_item=basket_item %}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <!--div class="detail__order-info">
                <div class="detail__delivery">100</div>
                <div class="detail__itogo">1 117 440</div>
            </div-->
            <div class="detail__courier">Курьер уже в пути!<br>Ориентировочное время доставки <span
                    class='detail__courier-time'>{{ order.delivery_at|date:"H:i" }}</span></div>
            {% if order.route_id %}
                <div class="detail__map">
                    <script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
                    <div id="map" style="height: 545px;"></div>
                    <script>
                        var placemark, coords;
                        var geo_lat = {{ order.address.geo_lat }};
                        var geo_lon = {{ order.address.geo_lon }};
                        ymaps.ready(function () {
                            var myMap = new ymaps.Map('map', {
                                center: [54.706419,55.997823],
                                zoom: 16,
                                controls: []
                            });
                            placemark = new ymaps.Placemark([54.706419,55.997823], {
                                balloonContent: 'Курьер'
                            });
                            myMap.geoObjects.add(placemark);
                            $(document).ready(function() {
                                var intervalID = setInterval( function() {
                                    $.getJSON('/current_point/{{ order.route_id }}/',function (data) {
                                        console.log(data);
                                        if (data.point) {
                                            if (data.point.lat === geo_lat && data.point.lon === geo_lon) clearInterval(intervalID);
                                            coords = [data.point.lat, data.point.lon];
                                            myMap.geoObjects.remove(placemark);
                                            placemark = new ymaps.Placemark(coords, {
                                                balloonContent: 'Курьер'
                                            });
                                            myMap.geoObjects.add(placemark);
                                            myMap.panTo(coords, {flying: 1,duration: 500});
                                        }
                                    });
                                } , 1000)
                            });
                        });
                    </script>
                </div>
            {% endif %}

        </div>
    </div>
{% endblock %}